# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'rovercontrol' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rovercontrol

  pod "MJPEGStreamLib"
  
  pod 'JxSwiftHelper', :path => '../../JxProjekte/JxSwiftHelper/'
  pod 'JxSwiftHelperForUiKit', :path => '../../JxProjekte/JxSwiftHelperForUiKit/'
  pod 'JxContentTable', :path => '../../JxProjekte/JxContentTable/'
  pod 'JxThemeManager', :path => '../../JxProjekte/JxThemeManager/'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      
      
      if config.build_settings['PRODUCT_NAME'] == 'PinchToZoomImageView'
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
  end
end
